# `nitpick` specific configuration.
# `nitpick` ensures that you have the same configuration
# in your own project.

# Make sure to install it with:
# `pip install nitpick`

["pyproject.toml".tool.black]
target-version = ['py310']
line-length = 120
include = '\.pyi?$'
preview = true
force_exclude = '''
(
  /(
    | migrations
  )/
  | urls\.py
)
'''

["setup.cfg".flake8]
ignore = "E203,D202,E501,W503"
max-line-length = 120
exclude = "node_modules"

["setup.cfg".isort]
profile = "black"
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

extra_standard_library = "arrow"
multi_line_output = 3
line_length = 120
include_trailing_comma = true

["setup.cfg".mypy]
# No untyped functions. Everything must be typed including returns.
disallow_untyped_defs = true

# Follow imports for type information but do not raise an error unless
# the file is explicitly type checked
# Valid values:skip/silent/normal/error.
follow_imports = "silent"

# Untyped imports are not imported as Any
disallow_any_unimported = true

# Allow imports to be untyped
# Phase 2: Once we have typed enough we will set to False and start requiring our 3rd party types to have types
ignore_missing_imports = true

# Untyped decorators will make a function untyped. This enforces decorators to be typed correctly.
disallow_untyped_decorators = true
disallow_untyped_calls = true

# Ensure even untyped functions are type checked
check_untyped_defs = true

strict_optional = true
strict_equality = true

# This disallows automatic reexporting after importing a module.
implicit_reexport = true

# We have to specify `Optional`
no_implicit_optional = true

# We want to see the error code
show_error_codes = true

# Warnings
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true
warn_return_any = true


###### Precommits

## RUFF
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/charliermarsh/ruff-pre-commit"
rev = "latest"

[[".pre-commit-config.yaml".repos.hooks]]
id = "ruff-fix"
args = ["--select", "F401", "--fix"]

# F401 Remove unused imports
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/charliermarsh/ruff-pre-commit"
rev = "latest"

[[".pre-commit-config.yaml".repos.hooks]]
id = "ruff-check"

# BLACK
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/psf/black"
rev = "latest"

[[".pre-commit-config.yaml".repos.hooks]]
id = "black"

# ISORT
[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/PyCQA/isort"
rev = "latest"

[[".pre-commit-config.yaml".repos.hooks]]
id = "isort"

# MYPY
[[".pre-commit-config.yaml".repos]]
repo = "local"

[[".pre-commit-config.yaml".repos.hooks]]
id = "mypy"
args = ["--show-error-codes"]
name = "mypy"
entry = "poetry run mypy"
require_serial = true
language = "system"
types = ["python"]
