name: Shame Test
on:
  pull_request:

permissions:
  id-token: write # Required for federated aws oidc
  contents: read
  actions: read
  pull-requests: write


jobs:
  ci:
    uses: ./workflows/ci.yaml@main
    secrets: inherit
    with:
      command: some bad command
